config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  resources :users, only: [:index, :create, :update]
  get 'signup', to: 'users#new'
  get 'user_edit', to: 'users#edit'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'howto' , to: 'how_to_uses#index'
  
  resources :folders do
    resources :favorite_tweets
  end
  resources :favorite_users, only: [:index, :show, :new, :create, :destroy]
end

app/models/folder.rb
class Folder < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :position, presence: true, uniqueness: { scope: :user_id }
  
  belongs_to :user
  has_many :favorite_tweets, dependent: :destroy
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :require_user_logged_in
  before_action :find_folder, only: [:show, :edit, :update, :destroy]
  before_action :find_folders, only: [:index, :create]
  
  def index
  end

  def show
    exist_folder
    @favorite_tweets = @folder.favorite_tweets
  end

  def new
    @folder = current_user.folders.new
  end

  def create
    # foldersテーブルの最大positionから保存するpositionを計算
    @folders.any? ? position = current_user.folders.maximum(:position) + 1 : position = 1
    params[:folder][:position] = position
    
    @folder = current_user.folders.new(folder_params)
    if @folder.save
      flash[:success] = 'フォルダを追加しました'
      redirect_to folder_favorite_tweets_url(@folder)
    else
      flash.now[:danger] = 'フォルダの追加に失敗しました'
      render :new
    end
  end

  def edit
    exist_folder
  end

  def update
    if @folder.update(folder_params)
      flash[:success] = 'フォルダの名前を更新しました'
      redirect_to folder_favorite_tweets_url(@folder)
    else
      flash.now[:danger] = 'フォルダの名前の更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @folder.destroy
    flash[:success] = 'フォルダを削除しました'
    redirect_to folders_url
  end
  
  private
  
  def folder_params
    params.require(:folder).permit(:name, :position)
  end
  
  def find_folder
    @folder = current_user.folders.find_by(id: params[:id])
  end
  
  def find_folders
    @folders = current_user.folders.order(position: :asc)
  end
  
  def exist_folder
    if !@folder
      # ログインユーザ以外が作成したフォルダ、もしくは存在しないフォルダを指定した場合
      flash[:success] = '指定したフォルダは存在しません'
      redirect_to root_url
    end
  end
end

app/views/folders/_form.html.erb
<%= form_with(model: model) do |f| %>
  <%= render 'layouts/error_messages', model: model %>
  <div class="mb-3">
    <%= f.label :name, 'フォルダ名'%>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  
  <div>
    <% if request.path == '/folders/new' %>
      <%= f.submit '追加', class: 'btn btn-primary w-100' %>
    <% else %>
      <%= f.submit '更新', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<div class="text-center">
  <h1>フォルダ名を入力</h1>
</div>
<br>
<div class="text-center">
  <h3>変更前：<%= @folder.name %></h3>
</div>
<div class="row mb-5">
  <div class="col-sm-6 offset-sm-3">
    <%= render 'form', model: @folder %>
  </div>
</div>
<div class="row">
  <div class="col-sm-2 offset-sm-10">
    <%= link_to '戻る', folder_path(@folder), class: 'btn btn-primary rounded-pill w-100' %>
  </div>
</div>

app/views/folders/index.html.erb
<div class="row">
  <div class="col-sm-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <%= link_to 'お気に入り', folders_path, class: 'nav-link active' %>
      </li>
      <li>
        <%= link_to 'ユーザー', favorite_users_path, class: 'nav-link' %>
      </li>
    </ul>
    <table class="table table-bordered">
      <% @folders.each do |folder| %>
        <tr>
          <td><%= link_to folder.name, folder_favorite_tweets_path(folder), class: 'nav-link' %></td>
          <td class="text-center"><%= link_to image_tag('pencil-square.svg', alt: 'edit'), folder, class: 'btn' %></td>
        </tr>
      <% end %>
      <tr>
        <td colspan="2" class="text-center">
          <%= link_to '＋', new_folder_path, class: 'btn btn-primary rounded-pill w-50' %>
        </td>
      </tr>
    </table>
  </div>
  
  <div class="col-sm-9">
  </div>
</div>

app/views/folders/new.html.erb
<div class="text-center">
  <h1>フォルダ名を入力</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3 mb-5">
    <%= render 'form', model: @folder %>
  </div>
</div>
<div class="row">
  <div class="col-sm-2 offset-sm-10">
    <%= link_to '戻る', folders_path, class: 'btn btn-primary rounded-pill w-100' %>
  </div>
</div>

app/views/folders/show.html.erb
<div class="text-center mb-3 border-bottom">
  <h1>フォルダ詳細</h1>
</div>

<div class="text-center ps-5 pe-5 mb-5">
  <h4>フォルダ名：<%= @folder.name %></h4>
  <div class="row">
    <div class="overflow-auto mb-3 col-sm-10 offset-1" style="height: 500px">
      <table class="table table-bordered">
        <% @favorite_tweets.each do |favorite_tweet| %>
          <tr>
            <td><%= favorite_tweet.tweet.html_safe %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="row">
    <%= link_to '編集', edit_folder_path(@folder), class: 'btn btn-primary col-sm-3 offset-sm-2' %>
    <%= link_to '削除', @folder, method: :delete, data: {confirm: "フォルダを削除するとツイートのお気に入りが全て解除されます。\n本当によろしいですか？"}, class: 'btn btn-danger col-sm-3 offset-sm-2' %>
  </div>
</div>
<div class="row">
  <div class="col-sm-2 offset-sm-10">
    <%= link_to '戻る', folder_favorite_tweets_path(@folder), class: 'btn btn-primary rounded-pill w-100' %>
  </div>
</div>