config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  resources :users, only: [:index, :create, :update]
  get 'signup', to: 'users#new'
  get 'user_edit', to: 'users#edit'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'howto' , to: 'how_to_uses#index'
  
  resources :folders do
    resources :favorite_tweets
  end
  resources :favorite_users, only: [:index, :show, :new, :create, :destroy]
end

app/models/favorite_tweet.rb
class FavoriteTweet < ApplicationRecord
  validates :tweet, presence: true, length: { maximum: 3000 }
  validates :position, presence: { scope: :folder_id }
  
  belongs_to :folder
end

app/controllers/favorite_tweets_controller.rb
class FavoriteTweetsController < ApplicationController
  before_action :require_user_logged_in
  before_action :find_folder, only: [:index, :show, :new, :create]
  
  def index
    @folders = current_user.folders.order(position: :asc) # フォルダ一覧表示用
    
    if !@folder
      # ログインユーザ以外が作成したフォルダ、もしくは存在しないフォルダを指定した場合
      flash[:success] = '指定したフォルダは存在しません'
      redirect_to root_url
    else
      @favorite_tweets = @folder.favorite_tweets.order(position: :asc)
    end
  end

  def show
    if !@folder
      flash[:success] = '指定したフォルダは存在しません'
      redirect_to root_url
    else
      @favorite_tweet = @folder.favorite_tweets.find_by(id: params[:id])
      if !@favorite_tweet
        # ログインユーザ以外が追加したツイート、もしくは存在しないツイートを指定した場合
        flash[:success] = '指定したツイートは存在しません'
        redirect_to folder_favorite_tweets_url(@folder)
      end
    end
  end

  def new
    @favorite_tweet = @folder.favorite_tweets.new
  end

  def create
    # 入力値から埋め込み用HTMLを作成
    begin
      create_uri(params[:favorite_tweet][:tweet])
    rescue Exception => e
      flash.now[:warning] = '入力したURLが間違っています'
    end
    params[:favorite_tweet][:tweet] = @oembed_tweet
    
    # 保存先フォルダの最大positionから保存するpositionを取得
    @folder.favorite_tweets.any? ? position = @folder.favorite_tweets.maximum(:position) + 1 : position = 1
    params[:favorite_tweet][:position] = position
    
    @favorite_tweet = @folder.favorite_tweets.new(favorite_tweet_params)
    
    if @favorite_tweet.save
      flash[:success] = 'ツイートをお気に入りに登録しました'
      redirect_to folder_favorite_tweets_url(@folder)
    else
      flash[:danger] = 'お気に入りの登録に失敗しました'
      render :new
    end
  end

  def edit
    @folder = current_user.folders.find_by(id: params[:folder_id])
    if !@folder
      flash[:success] = '指定したフォルダは存在しません'
      redirect_to root_url
    else
      @favorite_tweet = @folder.favorite_tweets.find_by(id: params[:id])
      if !@favorite_tweet
        # ログインユーザ以外が追加したツイート、もしくは存在しないツイートを指定した場合
        flash[:success] = '指定したツイートは存在しません'
        redirect_to folder_favorite_tweets_url(@folder)
      else
        folders = current_user.folders.order(position: :asc)
        @folder_list = [] # プルダウンリスト表示用
        
        folders.each do |folder|
          @folder_list.push([folder.name, folder.id])
        end
      end
    end
  end

  def update
    edit_folder = params[:favorite_tweet][:edit_folder]
    params[:favorite_tweet].delete("edit_folder")   # DBへの保存時に必要ないパラメータのため削除
    
    if edit_folder == 'move'
      # お気に入りツイートのフォルダ移動の場合
      @folder = current_user.folders.find_by(id: params[:folder_id])
      @favorite_tweet = @folder.favorite_tweets.find_by(id: params[:id])
      
      if @favorite_tweet.update(favorite_tweet_params)
        flash[:success] = 'お気に入りツイートを移動しました'
        redirect_to folder_favorite_tweets_url(params[:favorite_tweet][:folder_id])
      else
        flash.now[:danger] = 'お気に入りツイートの移動に失敗しました'
        render :edit
      end
    else
      # お気に入りツイートのコピーの場合、保存するパラメータを設定
      orginal_folder = current_user.folders.find_by(id: params[:folder_id])
      original_favorite_tweet = orginal_folder.favorite_tweets.find_by(id: params[:id])
      params[:favorite_tweet][:tweet] = original_favorite_tweet.tweet
      
      # コピー先foldersテーブルの最大positionから保存するpositionを計算
      @folder = current_user.folders.find_by(id: params[:favorite_tweet][:folder_id])
      @folder.favorite_tweets.any? ? position = @folder.favorite_tweets.maximum(:position) + 1 : position = 1
      params[:favorite_tweet][:position] = position
      
      @favorite_tweet = @folder.favorite_tweets.new(favorite_tweet_params)
      
      if @favorite_tweet.save
        flash[:success] = "ツイートを#{@folder.name}フォルダにコピーしました。"
        redirect_to folder_favorite_tweets_url(@folder)
      else
        folders = current_user.folders.order(position: :asc)
        @folder_list = [] # プルダウンリスト表示用
        
        folders.each do |folder|
          @folder_list.push([folder.name, folder.id])
        end
        
        flash.now[:danger] = 'ツイートのコピーに失敗しました'
        render :edit
      end
    end
    
  end

  def destroy
    @folders = current_user.folders.order(position: :asc) # index表示用
    @folder = current_user.folders.find_by(id: params[:folder_id]) # index選択済みフォルダ判定用
    
    @favorite_tweet = @folder.favorite_tweets.find_by(id: params[:id])
    @favorite_tweet.destroy
    flash[:success] = 'お気に入りから削除しました'
    redirect_to folder_favorite_tweets_url(@folder, @favorite_tweet)
  end
  
  private
  
  def favorite_tweet_params
    params.require(:favorite_tweet).permit(:tweet, :position, :folder_id)
  end
  
  def find_folder
    @folder = current_user.folders.find_by(id: params[:folder_id])
  end
  
  # 入力されたURLから埋め込みHTMLを作成
  def create_uri(tweet)
    tweet_id = tweet.match(/\/status\/(.*)/)[1]
    if tweet_id.include?("status")
      # アカウントIDがstatusであるユーザの場合の追加処理
      tweet_id = tweet_id.match(/status\/(.*)/)[1]
    end
    url = "https://publish.twitter.com/oembed?url=https%3A%2F%2Ftwitter.com%2FInterior%2Fstatus%2F#{tweet_id}"

    json_response = JSON.parse(OpenURI.open_uri(url).read)
    @oembed_tweet = json_response['html']
  end
end

app/views/favorite_tweets/edit.html.erb
<div class="text-center mb-3 border-bottom">
  <h1>お気に入りツイートの移動・コピー</h1>
</div>
<div class="text-center mb-5">
  <h3>フォルダ名:<%= @folder.name %></h3>
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= @favorite_tweet.tweet.html_safe %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= form_with(model: [@folder, @favorite_tweet], url: folder_favorite_tweet_path) do |f| %>
        <%= render 'layouts/error_messages', model: @favorite_tweet %>
        <div class="mb-3">
          <%= f.label :folder_id, '移動先フォルダ名' %>
          <%= f.select :folder_id, @folder_list, {}, class: 'form-select' %>

          <br>
          <%= f.radio_button :edit_folder, :move, checked: true %>
          <%= f.label :edit_folder, '移動', {value: :move, style: "display: inline-block;"} %>
          <%= f.radio_button :edit_folder, :copy %>
          <%= f.label :edit_folder, 'コピー', {value: :copy, style: "display: inline-block;"} %>

        </div>
        
        <div>
          <%= f.submit '更新', class: 'btn btn-primary w-100' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-2 offset-sm-10">
    <%= link_to '戻る', folder_favorite_tweet_path(@folder, @favorite_tweet), class: 'btn btn-primary rounded-pill w-100' %>
  </div>
</div>

app/views/favorite_tweets/index.html.erb
<div class="row">
  <div class="col-sm-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <%= link_to 'お気に入り', folders_path, class: 'nav-link active' %>
      </li>
      <li>
        <%= link_to 'ユーザー', favorite_users_path, class: 'nav-link' %>
      </li>
    </ul>
    <table class="table table-bordered">
      <% @folders.each do |folder| %>
        <tr>
          <td><%= link_to folder.name, folder_favorite_tweets_path(folder), class: "nav-link #{"text-muted" if request.fullpath.gsub('/folders/', '').gsub('/favorite_tweets', '') != folder.id.to_s}" %></td>
          <td class="text-center"><%= link_to image_tag('pencil-square.svg', alt: 'edit'), folder, class: 'btn' %></td>
        </tr>
      <% end %>
      <tr>
        <td class="text-center" colspan="2">
          <%= link_to '＋', new_folder_path, class: 'btn btn-primary rounded-pill w-50' %>
        </td>
      </tr>
    </table>
  </div>
  <div class="col-sm-9 mb-3 overflow-auto" style="height:800px;" >
    <div class="text-center mb-3">
      <%= link_to '＋', new_folder_favorite_tweet_path, class: 'btn btn-primary rounded-pill w-50' %>
    </div>
    <table class="table table-bordered">
      <% @favorite_tweets.each do |favorite_tweet| %>
        <tr>
          <td><%= favorite_tweet.tweet.html_safe %></td>
          <td class="align-middle"><%= link_to (image_tag 'pencil-square.svg', alt: 'edit'), folder_favorite_tweet_path(@folder, favorite_tweet), class: 'nav-link' %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/favorite_tweets/new.html.erb
<div class="text-center mb-3 border-bottom">
  <h1>お気に入りツイートを保存</h1>
</div>
<div class="row mb-5">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @favorite_tweet, url: folder_favorite_tweets_path) do |f| %>
      <div class="mb-3">
        <%= f.label :tweet, 'お気に入り登録したいツイートのURL' %>
        <%= f.text_field :tweet, class: 'form-control' %>
      </div>
      
      <div>
        <%= f.submit '追加', class: 'btn btn-primary w-100' %>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-sm-2 offset-sm-10">
    <%= link_to '戻る', folder_favorite_tweets_path, class: 'btn btn-primary rounded-pill w-100' %>
  </div>
</div>

app/views/favorite_tweets/show.html.erb
<div class="text-center mb-3 border-bottom">
  <h1>お気に入りツイート</h1>
</div>
<div class="text-center mb-5">
  <h4>フォルダ名：<%= @folder.name %></h4>
  <div class="row">
    <div class=" col-sm-6 offset-sm-3">
      <%= @favorite_tweet.tweet.html_safe %>
    </div>
  </div>
  <div class="row">
    <%= link_to '編集', edit_folder_favorite_tweet_path(@folder, @favorite_tweet), class: 'btn btn-primary col-sm-3 offset-2' %>
    <%= link_to '削除', folder_favorite_tweet_path(@folder, @favorite_tweet), method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger col-sm-3 offset-2' %>
  </div>
</div>
<div class="row">
  <div class="col-sm-2 offset-sm-10">
    <%= link_to '戻る', folder_favorite_tweets_path, class: 'btn btn-primary rounded-pill w-100' %>
  </div>
</div>