config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  resources :users, only: [:index, :create, :update]
  get 'signup', to: 'users#new'
  get 'user_edit', to: 'users#edit'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'howto' , to: 'how_to_uses#index'
  
  resources :folders do
    resources :favorite_tweets
  end
  resources :favorite_users, only: [:index, :show, :new, :create, :destroy]
end

app/models/favorite_user.rb
class FavoriteUser < ApplicationRecord
  validates :twitter_account, presence: true, length: { maximum: 100 }
  validates :position, presence: { scope: :user_id}
  
  belongs_to :user
end

app/controllers/favorite_users_controller.rb
class FavoriteUsersController < ApplicationController
  before_action :require_user_logged_in
  before_action :find_favorite_users, only: [:index, :show, :create]
  
  def index
  end

  def show
    @favorite_user = current_user.favorite_users.find_by(id: params[:id])
  end

  def new
    @favorite_user = current_user.favorite_users.new
  end

  def create
    # favorite_usersテーブルの最大positionから保存するpositionを計算
    current_user.favorite_users.maximum(:position).nil? ? position = 1 : position = current_user.favorite_users.maximum(:position) + 1
    params[:favorite_user][:position] = position

    @favorite_user = current_user.favorite_users.new(favorite_user_params)
    if @favorite_user.save
      flash[:success] = 'ユーザーを追加しました'
      redirect_to favorite_user_url(@favorite_user)
    else
      flash.now[:danger] = 'ユーザーの追加に失敗しました'
      render :new
    end
  end

  def destroy
    @favorite_user = current_user.favorite_users.find_by(id: params[:id])
    @favorite_user.destroy
    flash[:success] = 'ユーザーを削除しました'
    redirect_to favorite_users_url
  end
  
  private
  
  def favorite_user_params
    params.require(:favorite_user).permit(:twitter_account, :position)
  end
  
  def find_favorite_users
    @favorite_users = current_user.favorite_users.order(position: :asc)
  end
end

app/views/favorite_users/index.html.erb
<div class="row">
  <div class="col-sm-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <%= link_to 'お気に入り', folders_path, class: 'nav-link' %>
      </li>
      <li>
        <%= link_to 'ユーザー', favorite_users_path, class: 'nav-link active' %>
      </li>
    </ul>
    <table class="table table-bordered">
      <% @favorite_users.each do |favorite_user| %>
        <tr>
          <td><%= link_to favorite_user.twitter_account, favorite_user %></td>
          <td class="text-center"><%= link_to (image_tag 'trash3.svg', alt: 'delete'), favorite_user, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %></td>
        </tr>
      <% end %>
      <tr>
        <td class="text-center" colspan="2"><%= link_to '＋', new_favorite_user_path, class: 'btn btn-primary rounded-pill  w-50' %></td>
      </tr>
    </table>
  </div>
</div>

app/views/favorite_users/new.html.erb
<div class="text-center mb-3 border-bottom">
  <h1>ユーザー追加</h1>
</div>
<div class="mb-5">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= form_with(model: @favorite_user) do |f| %>
        <%= render 'layouts/error_messages', model: @favorite_user %>
        <div class="mb-3">
          <div class="row align-items-end">
            <div class="col-sm-3">
              <%= f.label :twitter_account, 'ユーザー名'%>
            </div>
            <div class="col-sm-9">
              <p>※Twitterのホーム画面で太字のアカウント名の下にある「＠」から始まっているもの</p>
            </div>
          </div>
          <%= f.text_field :twitter_account, class: 'form-control' %>
        </div>
        
        <div>
          <%= f.submit '追加', class: 'btn btn-primary w-100' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-2 offset-sm-10">
    <%= link_to '戻る', favorite_users_path, class: 'btn btn-primary rounded-pill w-100' %>
  </div>
</div>

app/views/favorite_users/show.html.erb
<div class="row">
  <div class="col-sm-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <%= link_to 'お気に入り', folders_path, class: 'nav-link' %>
      </li>
      <li>
        <%= link_to 'ユーザー', favorite_users_path, class: 'nav-link active' %>
      </li>
    </ul>
    <table class="table table-bordered">
      <% @favorite_users.each do |favorite_user| %>
        <tr>
          <td><%= link_to favorite_user.twitter_account, favorite_user, class: "nav-link #{"text-muted" if request.fullpath.gsub('/favorite_users/', '') != favorite_user.id.to_s}" %></td>
          <td class="text-center"><%= link_to (image_tag 'trash3.svg', alt: 'delete'), favorite_user, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %></td>
        </tr>
      <% end %>
      <tr>
        <td colspan="2" class="text-center"><%= link_to '＋', new_favorite_user_path, class: 'btn btn-primary rounded-pill w-50' %></td>
      </tr>
    </table>
  </div>
  
  <div class="col-sm-9 overflow-auto mb-3" style="height:800px;">
    <a class="twitter-timeline" href="https://twitter.com/<%= @favorite_user.twitter_account %>?ref_src=twsrc%5Etfw">Tweets by <%= @favorite_user.twitter_account %></a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>
</div>