config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  resources :users, only: [:index, :create, :update]
  get 'signup', to: 'users#new'
  get 'user_edit', to: 'users#edit'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'howto' , to: 'how_to_uses#index'
  
  resources :folders do
    resources :favorite_tweets
  end
  resources :favorite_users, only: [:index, :show, :new, :create, :destroy]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">Twitter Lake</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <% if logged_in? %>
            <li class="nav-item"><%= link_to current_user.name, user_edit_path(current_user), class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'お問い合わせ', 'https://forms.gle/Awh9Uo48UgWNkyiU8', target: :_blank, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Logout', logout_path, method: :delete, data: { confirm: 'ログアウトしてよろしいですか？?' }, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to (image_tag '2021_Twitter-logo_blue_mini.png', alt: 'twitter-logo'), 'https://twitter.com/', target: :_blank, class: 'img-fluid' %></li>
          <% else %>
            <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Twitter-lake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>